name: flutter_ddd_concepts
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.0.3
  cupertino_icons: ^1.0.4
  dartz: ^0.10.1
  firebase_auth: ^3.3.10
  firebase_core: ^1.13.1
  cloud_firestore: ^3.1.10
  flutter_bloc: ^8.0.1
  freezed_annotation: ^1.1.0
  google_sign_in: ^5.2.4
  injectable: ^1.5.3
  get_it: ^7.2.0
  equatable: ^2.0.3
  another_flushbar: ^1.10.28
  uuid: ^3.0.6
  auto_route: ^3.2.4
  go_router: ^3.0.4
  kt_dart: ^0.10.0
  json_annotation: ^4.4.0
  styled_widget: ^0.4.0+3
  flutter_hooks: ^0.18.2+1
  time: ^2.1.0
  rxdart: ^0.27.3
  reorderables: ^0.4.3
  flutter_slidable: ^1.2.0
  implicitly_animated_reorderable_list: ^0.4.2
  provider: ^6.0.2

  

dev_dependencies:
  auto_route_generator: ^3.2.3
  
  build_runner: ^2.1.7
  flutter_lints: ^1.0.4
  # flutter_test:
  #   sdk: flutter
  freezed: ^1.1.1
  injectable_generator: ^1.5.3
  json_serializable: ^6.1.5
 

flutter:
  uses-material-design: true
